spring:
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}
    gateway:
      discovery:
        locator:
          enabled: true
      # For curl "http://<gateway>/predicatePath/**"
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/clientService/**
          filters:
            - RewritePath=/clientService/(?<path>.*), /$\{path}
        - id: generator-service
          uri: https://generator.swagger.io/
          predicates:
            - Path=/generatorService/**
          filters:
            - RewritePath=/generatorService/(?<path>.*), /$\{path}