spring:
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}
    gateway:
      discovery:
        locator:
          enabled: true
      # For curl "http://<gateway>/predicatePath/**"
      routes:
        - id: client-service-route
          uri: lb://client-service
          predicates:
            - Path=/predicatePath/**